name: insurerisk
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyterlab
  - notebook
  - ipykernel
  - scipy
  - pip
  - pip:
      - streamlit
      - shap
